import { PricingTier, ZodiacSign, Nakshatra } from './types';

export const ZODIAC_SIGNS: Record<ZodiacSign, { name: string; sanskrit: string; symbol: string; element: string; ruler: string }> = {
  aries: {
    name: 'Aries',
    sanskrit: 'Mesha',
    symbol: '♈',
    element: 'Fire',
    ruler: 'Mars',
  },
  taurus: {
    name: 'Taurus',
    sanskrit: 'Vrishabha',
    symbol: '♉',
    element: 'Earth',
    ruler: 'Venus',
  },
  gemini: {
    name: 'Gemini',
    sanskrit: 'Mithuna',
    symbol: '♊',
    element: 'Air',
    ruler: 'Mercury',
  },
  cancer: {
    name: 'Cancer',
    sanskrit: 'Karka',
    symbol: '♋',
    element: 'Water',
    ruler: 'Moon',
  },
  leo: {
    name: 'Leo',
    sanskrit: 'Simha',
    symbol: '♌',
    element: 'Fire',
    ruler: 'Sun',
  },
  virgo: {
    name: 'Virgo',
    sanskrit: 'Kanya',
    symbol: '♍',
    element: 'Earth',
    ruler: 'Mercury',
  },
  libra: {
    name: 'Libra',
    sanskrit: 'Tula',
    symbol: '♎',
    element: 'Air',
    ruler: 'Venus',
  },
  scorpio: {
    name: 'Scorpio',
    sanskrit: 'Vrishchika',
    symbol: '♏',
    element: 'Water',
    ruler: 'Mars',
  },
  sagittarius: {
    name: 'Sagittarius',
    sanskrit: 'Dhanu',
    symbol: '♐',
    element: 'Fire',
    ruler: 'Jupiter',
  },
  capricorn: {
    name: 'Capricorn',
    sanskrit: 'Makara',
    symbol: '♑',
    element: 'Earth',
    ruler: 'Saturn',
  },
  aquarius: {
    name: 'Aquarius',
    sanskrit: 'Kumbha',
    symbol: '♒',
    element: 'Air',
    ruler: 'Saturn',
  },
  pisces: {
    name: 'Pisces',
    sanskrit: 'Mina',
    symbol: '♓',
    element: 'Water',
    ruler: 'Jupiter',
  },
};

export const NAKSHATRAS: Record<Nakshatra, { name: string; number: number; ruler: string; deity: string; symbolism: string }> = {
  ashwini: {
    name: 'Ashwini',
    number: 1,
    ruler: 'Ketu',
    deity: 'Ashwins (Divine Physicians)',
    symbolism: 'Horse Head - swift movement and healing',
  },
  bharani: {
    name: 'Bharani',
    number: 2,
    ruler: 'Venus',
    deity: 'Yama (God of Death/Time)',
    symbolism: 'Yoni - creativity and cosmic reproduction',
  },
  krittika: {
    name: 'Krittika',
    number: 3,
    ruler: 'Sun',
    deity: 'Agni (God of Fire)',
    symbolism: 'Flame - purification and illumination',
  },
  rohini: {
    name: 'Rohini',
    number: 4,
    ruler: 'Moon',
    deity: 'Brahma (Creator)',
    symbolism: 'Chariot/Ox Cart - stability and growth',
  },
  mrigashira: {
    name: 'Mrigashira',
    number: 5,
    ruler: 'Mars',
    deity: 'Soma (Moon God)',
    symbolism: 'Deer Head - searching and curiosity',
  },
  ardra: {
    name: 'Ardra',
    number: 6,
    ruler: 'Rahu',
    deity: 'Rudra (Storm Form of Shiva)',
    symbolism: 'Teardrop - tears and transformation',
  },
  punarvasu: {
    name: 'Punarvasu',
    number: 7,
    ruler: 'Jupiter',
    deity: 'Aditi (Mother of Gods)',
    symbolism: 'Arrow/Bow - return and renewal',
  },
  pushya: {
    name: 'Pushya',
    number: 8,
    ruler: 'Saturn',
    deity: 'Brihaspati (Jupiter/Wisdom)',
    symbolism: 'Flower/Udder - nourishment and growth',
  },
  aslesha: {
    name: 'Aslesha',
    number: 9,
    ruler: 'Mercury',
    deity: 'Sarpas (Serpents)',
    symbolism: 'Serpent Coil - wisdom and introspection',
  },
  magha: {
    name: 'Magha',
    number: 10,
    ruler: 'Ketu',
    deity: 'Pitris (Ancestors)',
    symbolism: 'Throne - authority and legacy',
  },
  purva_phalguni: {
    name: 'Purva Phalguni',
    number: 11,
    ruler: 'Venus',
    deity: 'Aryaman (Friend/Patron)',
    symbolism: 'Hammock/Bed - pleasure and creativity',
  },
  uttara_phalguni: {
    name: 'Uttara Phalguni',
    number: 12,
    ruler: 'Sun',
    deity: 'Bhaga (Portion/Prosperity)',
    symbolism: 'Cart/Platform - strength and stability',
  },
  hasta: {
    name: 'Hasta',
    number: 13,
    ruler: 'Mercury',
    deity: 'Savitar (Sun - Divine Impulse)',
    symbolism: 'Hand - skill and dexterity',
  },
  chitra: {
    name: 'Chitra',
    number: 14,
    ruler: 'Mars',
    deity: 'Tvashtar (Cosmic Architect)',
    symbolism: 'Jewel/Pearl - creation and craftsmanship',
  },
  swati: {
    name: 'Swati',
    number: 15,
    ruler: 'Rahu',
    deity: 'Vayu (God of Wind)',
    symbolism: 'Sword/Blade - independence and flexibility',
  },
  vishakha: {
    name: 'Vishakha',
    number: 16,
    ruler: 'Jupiter',
    deity: 'Indra & Agni (Power and Fire)',
    symbolism: 'Arch/Gate - success and ambition',
  },
  anuradha: {
    name: 'Anuradha',
    number: 17,
    ruler: 'Saturn',
    deity: 'Mitra (Friend/Devotion)',
    symbolism: 'Lotus - prosperity and discipline',
  },
  jyeshtha: {
    name: 'Jyeshtha',
    number: 18,
    ruler: 'Mercury',
    deity: 'Indra (King of Gods)',
    symbolism: 'Amulet/Earring - protection and leadership',
  },
  mula: {
    name: 'Mula',
    number: 19,
    ruler: 'Ketu',
    deity: 'Nirriti (Destruction/Dissolution)',
    symbolism: 'Root - foundation and depth',
  },
  purva_shadha: {
    name: 'Purva Shadha',
    number: 20,
    ruler: 'Venus',
    deity: 'Apas (Waters)',
    symbolism: 'Fan/Winnowing - purification and blessings',
  },
  uttara_shadha: {
    name: 'Uttara Shadha',
    number: 21,
    ruler: 'Sun',
    deity: 'Vishvadevas (All Gods)',
    symbolism: 'Elephant Tusk - victory and stability',
  },
  shravana: {
    name: 'Shravana',
    number: 22,
    ruler: 'Moon',
    deity: 'Vishnu (Sustenance)',
    symbolism: 'Ear/Three Footprints - listening and foundation',
  },
  dhanishtha: {
    name: 'Dhanishtha',
    number: 23,
    ruler: 'Mars',
    deity: 'Vasus (Wealth Deities)',
    symbolism: 'Drum - wealth and prosperity',
  },
  shatabhisha: {
    name: 'Shatabhisha',
    number: 24,
    ruler: 'Rahu',
    deity: 'Varuna (Ocean God)',
    symbolism: 'Star/Hundred Physicians - healing and mystery',
  },
  purva_bhadrapada: {
    name: 'Purva Bhadrapada',
    number: 25,
    ruler: 'Jupiter',
    deity: 'Aja Ekapada (One-Footed Goat)',
    symbolism: 'Sword/Twins - ferocity and duality',
  },
  uttara_bhadrapada: {
    name: 'Uttara Bhadrapada',
    number: 26,
    ruler: 'Saturn',
    deity: 'Ahir Budhyana (Cosmic Serpent)',
    symbolism: 'Twins/Backend of Bed - spiritual fulfillment',
  },
  revati: {
    name: 'Revati',
    number: 27,
    ruler: 'Mercury',
    deity: 'Pushan (Nourisher/Guide)',
    symbolism: 'Fish/Drum - abundance and protection',
  },
};

export const PLANETS = [
  {
    name: 'Sun',
    sanskrit: 'Surya',
    symbol: '☉',
    day: 'Sunday',
    element: 'Fire',
    gender: 'Male',
    caste: 'Kshatriya',
    temperament: 'Sanguine',
    moola_trikona: 'Leo',
    exaltation: 'Aries',
    debilitation: 'Libra',
  },
  {
    name: 'Moon',
    sanskrit: 'Chandra',
    symbol: '☽',
    day: 'Monday',
    element: 'Water',
    gender: 'Female',
    caste: 'Vaishya',
    temperament: 'Phlegmatic',
    moola_trikona: 'Taurus',
    exaltation: 'Taurus',
    debilitation: 'Scorpio',
  },
  {
    name: 'Mars',
    sanskrit: 'Mangal',
    symbol: '♂',
    day: 'Tuesday',
    element: 'Fire',
    gender: 'Male',
    caste: 'Kshatriya',
    temperament: 'Choleric',
    moola_trikona: 'Aries',
    exaltation: 'Capricorn',
    debilitation: 'Cancer',
  },
  {
    name: 'Mercury',
    sanskrit: 'Budha',
    symbol: '☿',
    day: 'Wednesday',
    element: 'Earth',
    gender: 'Neutral',
    caste: 'Vaishya',
    temperament: 'Sanguine',
    moola_trikona: 'Virgo',
    exaltation: 'Virgo',
    debilitation: 'Pisces',
  },
  {
    name: 'Jupiter',
    sanskrit: 'Guru',
    symbol: '♃',
    day: 'Thursday',
    element: 'Air',
    gender: 'Male',
    caste: 'Brahmin',
    temperament: 'Sanguine',
    moola_trikona: 'Sagittarius',
    exaltation: 'Cancer',
    debilitation: 'Capricorn',
  },
  {
    name: 'Venus',
    sanskrit: 'Shukra',
    symbol: '♀',
    day: 'Friday',
    element: 'Water',
    gender: 'Female',
    caste: 'Vaishya',
    temperament: 'Phlegmatic',
    moola_trikona: 'Libra',
    exaltation: 'Pisces',
    debilitation: 'Virgo',
  },
  {
    name: 'Saturn',
    sanskrit: 'Shani',
    symbol: '♄',
    day: 'Saturday',
    element: 'Air',
    gender: 'Male',
    caste: 'Shudra',
    temperament: 'Melancholic',
    moola_trikona: 'Aquarius',
    exaltation: 'Libra',
    debilitation: 'Aries',
  },
  {
    name: 'Rahu',
    sanskrit: 'Rahu',
    symbol: '☊',
    day: 'Saturday',
    element: 'Air',
    gender: 'Male',
    caste: 'Shudra',
    temperament: 'Choleric',
    moola_trikona: 'Aquarius',
    exaltation: 'Taurus',
    debilitation: 'Scorpio',
  },
  {
    name: 'Ketu',
    sanskrit: 'Ketu',
    symbol: '☋',
    day: 'Thursday',
    element: 'Fire',
    gender: 'Female',
    caste: 'Shudra',
    temperament: 'Melancholic',
    moola_trikona: 'Pisces',
    exaltation: 'Scorpio',
    debilitation: 'Taurus',
  },
];

export const HOUSES = [
  {
    number: 1,
    name: 'Ascendant (Lagna)',
    significance: 'Self, personality, appearance, health, character',
  },
  {
    number: 2,
    name: 'Wealth',
    significance: 'Finance, family, speech, food, assets',
  },
  {
    number: 3,
    name: 'Courage & Siblings',
    significance: 'Siblings, communication, short journeys, courage',
  },
  {
    number: 4,
    name: 'Mother & Home',
    significance: 'Mother, home, property, vehicles, education',
  },
  {
    number: 5,
    name: 'Children & Creativity',
    significance: 'Children, romance, creativity, speculation, intelligence',
  },
  {
    number: 6,
    name: 'Health & Enemies',
    significance: 'Health, debts, enemies, disease, service',
  },
  {
    number: 7,
    name: 'Marriage & Partnerships',
    significance: 'Spouse, marriage, partnerships, business relations',
  },
  {
    number: 8,
    name: 'Longevity & Death',
    significance: 'Lifespan, sudden events, inheritance, occult',
  },
  {
    number: 9,
    name: 'Fortune & Travel',
    significance: 'Luck, religion, long journeys, guru, philosophy',
  },
  {
    number: 10,
    name: 'Career & Status',
    significance: 'Career, reputation, authority, public image',
  },
  {
    number: 11,
    name: 'Gains & Friendship',
    significance: 'Gains, income, friends, social circles',
  },
  {
    number: 12,
    name: 'Loss & Spirituality',
    significance: 'Losses, expenditure, secrets, spirituality, foreign lands',
  },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'Basic astrology features for beginners',
    price: 0,
    currency: 'INR',
    type: 'one-time',
    features: [
      'Daily horoscope for your zodiac sign',
      'Basic birth chart visualization',
      'Lunar calendar view',
      'General astrology articles',
    ],
    reportTypes: ['daily_horoscope'],
    validityDays: 365,
  },
  {
    id: 'kundli_basic',
    name: 'Detailed Kundli',
    description: 'Comprehensive birth chart analysis',
    price: 49,
    currency: 'INR',
    type: 'one-time',
    features: [
      'Complete birth chart with planetary positions',
      'Nakshatra and house analysis',
      'Dasha period calculations',
      'Yoga and Dosha identification',
      'Personalized insights',
      'PDF download of your chart',
    ],
    reportTypes: ['kundli'],
    validityDays: 365,
  },
  {
    id: 'kundli_premium',
    name: 'Premium Kundli',
    description: 'In-depth birth chart with detailed analysis',
    price: 99,
    currency: 'INR',
    type: 'one-time',
    features: [
      'All Detailed Kundli features',
      'Advanced astrological calculations',
      'Career and finance analysis',
      'Health predictions',
      'Remedial measures and solutions',
      'Consultant support via chat',
    ],
    reportTypes: ['kundli', 'career', 'health', 'finance'],
    validityDays: 365,
    popular: true,
  },
  {
    id: 'compatibility_basic',
    name: 'Compatibility Check',
    description: 'Check relationship compatibility',
    price: 79,
    currency: 'INR',
    type: 'one-time',
    features: [
      'Relationship compatibility analysis',
      'Guna Milan (gun matching) score',
      'Dosha compatibility check',
      'Mangal Dosha assessment',
      'Detailed compatibility report',
      'Remedial solutions if needed',
    ],
    reportTypes: ['compatibility'],
    validityDays: 365,
  },
  {
    id: 'compatibility_premium',
    name: 'Premium Compatibility',
    description: 'In-depth relationship analysis',
    price: 149,
    currency: 'INR',
    type: 'one-time',
    features: [
      'All Compatibility Check features',
      'Future prediction timeline',
      'Dasha compatibility analysis',
      'Progressed chart compatibility',
      'Detailed marriage timing forecast',
      'Personalized remedial rituals',
      'Expert astrologer consultation',
    ],
    reportTypes: ['compatibility'],
    validityDays: 365,
    popular: true,
  },
  {
    id: 'annual_horoscope',
    name: 'Annual Horoscope',
    description: 'Year-long predictions and insights',
    price: 99,
    currency: 'INR',
    type: 'one-time',
    features: [
      'Month-by-month predictions',
      'Opportunities and challenges forecast',
      'Lucky dates and times',
      'Dasha and transit analysis',
      'Career and relationship outlook',
      'Remedial recommendations',
    ],
    reportTypes: ['annual_horoscope'],
    validityDays: 365,
  },
  {
    id: 'annual_horoscope_premium',
    name: 'Premium Annual Horoscope',
    description: 'Comprehensive yearly guidance',
    price: 199,
    currency: 'INR',
    type: 'one-time',
    features: [
      'All Annual Horoscope features',
      'Weekly detailed predictions',
      'Transit effects on all life areas',
      'Advanced astrological remedies',
      'Video consultation with astrologer',
      'Personalized recommendations',
    ],
    reportTypes: ['annual_horoscope'],
    validityDays: 365,
    popular: true,
  },
  {
    id: 'monthly_subscription',
    name: 'Monthly Membership',
    description: 'Ongoing astrological guidance',
    price: 149,
    currency: 'INR',
    type: 'monthly',
    features: [
      'All horoscope reports monthly',
      'Weekly personalized readings',
      'Chat support with astrologer',
      'Live astrology sessions',
      'Custom remedies and rituals',
      'Birthday predictions',
      'Advanced transit reports',
    ],
    validityDays: 30,
  },
  {
    id: 'annual_subscription',
    name: 'Annual Membership',
    description: 'Best value yearly astrology access',
    price: 1199,
    currency: 'INR',
    type: 'annual',
    features: [
      'All Monthly Membership features',
      'Unlimited report access',
      'Priority astrologer support',
      'Monthly one-on-one consultations',
      'Advance warning system for major transits',
      'Family member profile access',
      'Exclusive events and webinars',
      'Best value - Save 34%',
    ],
    validityDays: 365,
    popular: true,
  },
];

export const ASTROLOGICAL_REMEDIES = {
  gemstones: [
    { name: 'Ruby', planet: 'Sun', color: 'Red', benefits: 'Power, authority, health' },
    { name: 'Pearl', planet: 'Moon', color: 'White', benefits: 'Calmness, emotional balance' },
    { name: 'Red Coral', planet: 'Mars', color: 'Red', benefits: 'Courage, vitality' },
    { name: 'Emerald', planet: 'Mercury', color: 'Green', benefits: 'Communication, intellect' },
    { name: 'Yellow Sapphire', planet: 'Jupiter', color: 'Yellow', benefits: 'Wisdom, fortune' },
    { name: 'Diamond', planet: 'Venus', color: 'White', benefits: 'Love, prosperity' },
    { name: 'Blue Sapphire', planet: 'Saturn', color: 'Blue', benefits: 'Protection, stability' },
    { name: 'Hessonite', planet: 'Rahu', color: 'Honey', benefits: 'Grounding, clarity' },
    { name: 'Cat\'s Eye', planet: 'Ketu', color: 'Brown', benefits: 'Spiritual growth' },
  ],
  yantras: [
    { name: 'Shri Yantra', purpose: 'Prosperity and abundance' },
    { name: 'Kali Yantra', purpose: 'Protection and strength' },
    { name: 'Lakshmi Yantra', purpose: 'Wealth and success' },
    { name: 'Saraswati Yantra', purpose: 'Knowledge and wisdom' },
    { name: 'Durga Yantra', purpose: 'Victory and courage' },
  ],
  mantras: [
    { planet: 'Sun', mantra: 'Om Suryaya Namaha' },
    { planet: 'Moon', mantra: 'Om Somaya Namaha' },
    { planet: 'Mars', mantra: 'Om Angarakaya Namaha' },
    { planet: 'Mercury', mantra: 'Om Budhaya Namaha' },
    { planet: 'Jupiter', mantra: 'Om Brihaspataye Namaha' },
    { planet: 'Venus', mantra: 'Om Shukraya Namaha' },
    { planet: 'Saturn', mantra: 'Om Shanaischaraya Namaha' },
    { planet: 'Rahu', mantra: 'Om Rahave Namaha' },
    { planet: 'Ketu', mantra: 'Om Ketave Namaha' },
  ],
};

export const DASHAS = [
  { name: 'Vimshottari Dasha', duration: 120, description: 'Most commonly used dasha system' },
  { name: 'Ashtottari Dasha', duration: 108, description: 'Alternative major dasha period' },
  { name: 'Yogini Dasha', duration: 36, description: 'Used for quick events' },
  { name: 'Kalachakra Dasha', duration: 60, description: 'Based on lunar month' },
];
